[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]
# Here, you are allowing Foundry to run commands on your machine
# Keep this off as much as possible
ffi = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
